name: Backend - Tests

on:
  workflow_call:
    secrets:
      GITHUB_AUTH_TOKEN:
        description: "The GitHub Token."
        required: true
      CODECOV_TOKEN:
        description: 'Codecov Token'
        required: true
      SONAR_TOKEN:
        description: 'Sonar Token'
        required: true
      GOOGLE_SERVICE_ACCOUNT:
        description: 'Google Service Account'
        required: true

permissions:
  contents: write
  checks: write
  actions: read
  pull-requests: write

jobs:
  test:
    name: Backend - Tests
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        name: Checkout - Current ref
        with:
          fetch-depth: 0

      # Setup build
      - uses: kestra-io/actions/composite/setup-build@main
        name: Setup - Build
        id: build
        with:
          java-enabled: true
          node-enabled: true
          python-enabled: true

      - name: Gradle - compile and javadoc
        shell: bash
        run: |
          ./gradlew compileJava javadoc --parallel

      # Services
      - name: Setup - Start docker compose
        shell: bash
        run: docker compose -f docker-compose-ci.yml up -d

      # Gradle check
      - name: Gradle - check
        if: ${{ github.event.inputs.skip-test == 'false' || github.event.inputs.skip-test == '' }}
        shell: bash
        run: |
          ./gradlew check --parallel

      - name: Gradle - flakyTest
        if: ${{ github.event.inputs.skip-test == 'false' || github.event.inputs.skip-test == '' }}
        continue-on-error: true
        shell: bash
        run: |
          if [ -x ./gradlew ] && ./gradlew -q tasks --all | grep -q ':flakyTest'; then
            ./gradlew flakyTest
          else
            echo "ℹ️ flakyTest task does not exist in this old release branch, skipping"
          fi

      - name: comment PR with test report
        if: ${{ !cancelled() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
        run: npx --yes @kestra-io/kestra-devtools generateTestReportSummary --only-errors --ci $(pwd)

      - name: generate test report in logs and fail if any failed tests
        if: ${{ !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
        run: npx --yes @kestra-io/kestra-devtools generateTestReportSummary --only-errors --fail-on-error $(pwd)

      # Report Java
      # this will add a failed check if there is tests errors
      - name: Report - Java
        uses: kestra-io/actions/composite/report-java@main
        if: ${{ !cancelled() }}
        with:
          secrets: ${{ toJSON(secrets) }}